durability_types:
    unknown_durability: "&8&lDurability: &e&l%s &7/ &0&l&k%m"
    handsome_durability: "&b&lDurability &9> &f%s &7/ &f&l%m"
    spooky_durability: "&5&l&oDurability is &7(&o%s&r/&7&o%m&7)"
    scary_durability: "&7This item has only &c&o%s &7life left out of &f%m"
#   yourcustom_durability: "&eDurability&l: &b%s &7/ &9%m"

durability_notifier:
    unknown_durability: "&5&oYour durability: &f%s &8/ &o%m"
    handsome_durability: "&bDurability: &f%s &7/ &8%m"
#   durability_type: "&eYour notifier: &f%s &7of %m"

your_currency: "$"

repair_materials:
   diamond_items:
   - "DIAMOND"
   - "@SELFITEM"
   gold_items:
   - "GOLD_INGOT"
   - "@SELFITEM"
   iron_items:
   - "IRON_INGOT"
   - "@SELFITEM"
   wooden_items:
   - "OAK_PLANKS"
   - "SPRUCE_PLANKS"
   - "JUNGLE_PLANKS"
   - "BIRCH_PLANKS"
   - "ACACIA_PLANKS"
   - "DARK_OAK_PLANKS"
   - "@SELFITEM"
   stone_items:
   - "STONE"
   - "@SELFITEM"
   shear_item:
   - "IRON_INGOT"
   - "@SELFITEM"
   bow_item:
   - "STRING"
   - "STICK"
   - "@SELFITEM"
   flint_and_steel:
   - "FLINT"
   - "IRON_INGOT"
   - "@SELFITEM"
   trident_item:
   - "@SELFITEM"
# @SELFITEM is for same material
   
magicanvil_options:
   random_percentage_max: 2.0@10.5
   random_integer_max: 10@200
   repair_values:
       diamond:
         type: RANDOM_PERCENTAGE
         amount: 0
      # Random Percentage / Random Number doesn't count amounts.
       iron_ingot:
         type: PERCENTAGE
         amount: 20.0
       gold_ingot:
         type: PERCENTAGE
         amount: 25.0
       flint:
         type: RANDOM_INTEGER
         amount: 0
       string:
         type: PERCENTAGE
         amount: 11
       stick:
         type: PERCENTAGE
         amount: 15
       stone:
         type: INTEGER
         amount: 105
       oak_planks:
         type: PERCENTAGE
         amount: 10
       spruce_planks:
         type: PERCENTAGE
         amount: 10
       jungle_planks:
         type: PERCENTAGE
         amount: 10
       birch_planks:
         type: PERCENTAGE
         amount: 10
       dark_oak_planks:
         type: PERCENTAGE
         amount: 10
       acacia_planks:
         type: PERCENTAGE
         amount: 10
       same_material:
         type: PERCENTAGE
         amount: 35.0
durabilities:
   pickaxe:
     block_break: 1
     entity_hit: 2
   shovel:
     tile_grass: 1
     block_break: 1
     entity_hit: 2
   axe_item:
     block_break: 1
     entity_hit: 2
   hoes_item:
     tile_grass: 1
     entity_hit: 1
   swords_item:
     block_break: 2
     entity_hit: 1
# NEXT TO DO BELOW ,,,,,
   fishing_rod:
     item_reel: 1
     reeling_blocks: 2
     yank_item: 3
     yank_mob: 5
   shears:
     shear_sheeps: 2
   flint_and_steel:
     burn_up: 1
   bow_item:
     shooting_arrow: 1
   tridents:
     block_break: 2
   shield_item:
     use_minecrafts: true
     block_damage: 2
   